# Generated by Django 2.2.6 on 2019-10-19 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('d', 'Doação'), ('v', 'Voluntariado')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Apoiador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('pf', 'Pessoa Física'), ('pj', 'Pessoa Jurídica')], max_length=2)),
                ('registro', models.CharField(max_length=13)),
                ('endereco', models.CharField(max_length=90)),
                ('pontos', models.IntegerField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('cnpj', models.CharField(max_length=13)),
                ('endereco', models.CharField(max_length=90)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.FileField(upload_to='')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('apoiadores', models.ManyToManyField(related_name='badges', to='match.Apoiador')),
            ],
        ),
        migrations.CreateModel(
            name='AcaoApoiador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apoiadores', to='match.Acao')),
                ('apoiadores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='match.Apoiador')),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='match.Entidade')),
            ],
        ),
    ]
