# Generated by Django 2.2.6 on 2019-10-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(default='Brasil', max_length=50)),
                ('estado', models.CharField(choices=[('AC', 'AC'), ('CE', 'CE'), ('DF', 'DF'), ('TO', 'TO'), ('RS', 'RS'), ('SC', 'SC'), ('PR', 'PR'), ('PA', 'PA'), ('RO', 'RO'), ('RR', 'RR'), ('SE', 'SE'), ('PE', 'PE'), ('MT', 'MT'), ('MS', 'MS'), ('BA', 'BA'), ('RN', 'RN'), ('AM', 'AM'), ('SP', 'SP'), ('RJ', 'RJ'), ('MG', 'MG'), ('ES', 'ES'), ('GO', 'GO'), ('AL', 'AL'), ('AP', 'AP'), ('MA', 'MA'), ('PI', 'PI')], max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=300)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
