# Generated by Django 2.2.6 on 2019-10-19 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoiador',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='match.Endereco'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='match.Endereco'),
        ),
    ]
