# Generated by Django 2.2.6 on 2019-10-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_remove_entidade_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apoiador',
            name='username',
        ),
        migrations.AlterField(
            model_name='apoiador',
            name='registro',
            field=models.CharField(help_text='CPF, se pessoa física. CNPJ, se jurídica', max_length=13),
        ),
    ]
