# Generated by Django 2.2.6 on 2019-10-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_auto_20191019_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acaoapoiador',
            name='acao',
        ),
        migrations.AddField(
            model_name='acaoapoiador',
            name='nome',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acaoapoiador',
            name='tipo',
            field=models.CharField(choices=[('d', 'Doação'), ('v', 'Voluntariado')], default='d', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acaoapoiador',
            name='valor',
            field=models.IntegerField(default=0, help_text='Valor doado ou horas trabalhadas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apoiador',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
    ]
