# Generated by Django 2.2.6 on 2019-10-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_auto_20191019_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acao',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='acao',
            name='tipo',
        ),
    ]
