# Generated by Django 2.2.6 on 2019-10-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_auto_20191019_0703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acao',
        ),
    ]
