# Generated by Django 2.2.6 on 2019-10-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0011_entidade_interesses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidade',
            name='interesses',
        ),
        migrations.AddField(
            model_name='entidade',
            name='descricao',
            field=models.TextField(default='Uma instituição de caráter social'),
        ),
    ]
