# Generated by Django 2.2.6 on 2019-10-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0012_auto_20191019_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='interesses',
            field=models.ManyToManyField(to='match.Interesse'),
        ),
    ]
