# Generated by Django 2.2.6 on 2019-10-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0013_entidade_interesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoiador',
            name='descricao',
            field=models.TextField(default='Um apoiador de projetos para crianças'),
        ),
    ]
