# Generated by Django 2.2.6 on 2019-10-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0014_apoiador_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='apoiadores',
            field=models.ManyToManyField(blank=True, related_name='badges', to='match.Apoiador'),
        ),
    ]
